# Generated by Django 5.1.6 on 2025-04-11 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('length', models.CharField(choices=[('130', '130 cm'), ('145', '145 cm'), ('150', '150 cm'), ('165', '165 cm'), ('175', '175 cm')], max_length=3, null=True)),
                ('level', models.CharField(choices=[('begginer', 'A'), ('intermediate', 'B'), ('expert', 'C')], max_length=20, null=True)),
                ('banner', models.ImageField(blank=True, default='Equipment_photo/test.jpg', upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='reservations.category')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='reservations.equipment')),
            ],
        ),
    ]
