# Generated by Django 5.1.6 on 2025-03-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='level',
            field=models.CharField(choices=[('begginer', 'A'), ('intermediate', 'B'), ('expert', 'C')], max_length=20, null=True),
        ),
    ]
