# Generated by Django 5.1.6 on 2025-04-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='banner',
            field=models.ImageField(blank=True, default='equipment_photo/test.jpg', upload_to=''),
        ),
    ]
