# Generated by Django 5.1.6 on 2025-04-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_equipment_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='banner',
            field=models.ImageField(blank=True, default='Equipment_photo/test.jpg', upload_to=''),
        ),
    ]
