# Generated by Django 5.1.6 on 2025-04-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='length',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='level',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
