# Generated by Django 5.1.6 on 2025-04-13 12:18

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_equipment_length_alter_equipment_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
