# Generated by Django 5.1.6 on 2025-04-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_equipment_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='banner',
            field=models.ImageField(blank=True, default='test.jpg', upload_to=''),
        ),
    ]
