# Generated by Django 5.1.6 on 2025-04-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_cancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='cancelled',
            new_name='is_cancelled',
        ),
    ]
