# Generated by Django 5.1.6 on 2025-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_rename_cancelled_reservation_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='banner',
            field=models.ImageField(blank=True, default='test/test.jpg', upload_to=''),
        ),
    ]
