# Generated by Django 5.1.6 on 2025-05-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_equipment_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='banner',
            field=models.ImageField(blank=True, default='equipment_photo/test.jpg', upload_to=''),
        ),
    ]
