# Generated by Django 5.1.6 on 2025-05-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_equipment_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='length',
            field=models.CharField(choices=[('130', '130 cm'), ('135', '135 cm'), ('140', '140 cm'), ('145', '145 cm'), ('150', '150 cm'), ('155', '155 cm'), ('160', '160 cm'), ('165', '165 cm'), ('170', '170 cm'), ('175', '175 cm'), ('180', '180 cm'), ('185', '185 cm')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
    ]
