# Generated by Django 5.1.6 on 2025-05-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_equipment_length_alter_equipment_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='banner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
