# Generated by Django 5.1.6 on 2025-05-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_alter_equipment_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='banner',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
