# Generated by Django 5.1.6 on 2025-05-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_alter_equipment_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='banner',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
    ]
